# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

from snakemake.utils import validate


configfile: "config/config.yaml"


validate(config, "../schema/global_config_schema.yaml")

TARGETS = []


rule all:
    input:
        TARGETS,


include: "rules/bwamem2.smk"
include: "rules/duphold.smk"
include: "rules/fastqc.smk"
include: "rules/manta.smk"
include: "rules/multiqc.smk"

