# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a manifest file that contains
# one row per sample. It can be parsed easily via pandas.
manifest: "config/manifest.tsv"
sample-logbook: "resources/example_logbook.xlsx.xlsx"
sample-linking:
  sex: "config/sample_linking_sex.tsv"
  external-ids: "config/sample_linking_external_ids.tsv"
multiqc-read-config: "config/multiqc_read_config.yaml"
multiqc-alignment-config: "config/multiqc_alignment_config.yaml"
multiqc-calling-config: "config/multiqc_calling_config.yaml"
genome-build: "grch38"
apptainer-image-dir: "apptainer_images"

behaviors:
  use-containers: no
  aligner: "bwa"
  snv-caller: "deepvariant"
  sv-callers:
    - "manta"
    - "lumpy"
    - "delly"
  sv-ensemble:
    merge-tool: "svdb"
    min-count: 2
  sv-remove-breakends: yes
  outcome: "release"
  symlink-fastqs: no
  trim-adapters-before-alignment: yes
  assume-last-sample-sex: "female"
  export-directory: "/locus/data/external_data/research_experiments/pmgrc_u01"
  export-s3:
    bucket-name: "s3://pmgrc-gregor-data"
    profile-name: "ucigrant"

parameters:
  bwa:
    K: 120000000
  bwa-mem2:
    K: 120000000
  deepvariant:
    number-shards: 16
    docker-version: "1.4.0"
  manta:
    config-ini: "config/configManta.py.ini"
  tiddit:
    min-contig-size: 2000000

references:
  grch37:
    fasta: "s3://invitae-health-chameleon-dev/reference_data/grch37/human_g1k_v37_modified/human_g1k_v37_modified.fasta"
    exclusion-regions-bed: "https://github.com/Boyle-Lab/Blacklist/raw/master/lists/hg19-blacklist.v2.bed.gz"
    exons-gtf-gz: "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/genes/hg19.ncbiRefSeq.gtf.gz"
  grch38:
    fasta: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
    exclusion-regions-bed: "resources/grch38_encodelist_centromeres_telomeres.bed"
    exons-gtf-gz: "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/hg38.ncbiRefSeq.gtf.gz"
bqsr:
  grch37:
    known-indels-vcf-gz: "s3://broad-references/hg19/v0/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
    known-indels-vcf-gz-tbi: "s3://broad-references/hg19/v0/Mills_and_1000G_gold_standard.indels.b37.vcf.gz.tbi"
    dbsnp138-vcf: "s3://broad-references/hg19/v0/Homo_sapiens_assembly19.dbsnp138.vcf"
    dbsnp138-vcf-idx: "s3://broad-references/hg19/v0/Homo_sapiens_assembly19.dbsnp138.vcf.idx"
  grch38:
    known-indels-vcf-gz: "s3://broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
    known-indels-vcf-gz-tbi: "s3://broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"
    dbsnp138-vcf: "s3://broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf"
    dbsnp138-vcf-idx: "s3://broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf.idx"
dnascope:
  grch37:
    model: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/sentieon/SentieonDNAscopeModel1.1.model"
    dbsnp-vcf-gz: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/sentieon/dbsnp_138.b37.vcf.gz"
verifybamid2:
  grch37:
    db-V: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/verifybamid/VerifyBamID/resource/1000g.phase3.100k.b37.vcf.gz.dat.V"
    db-UD: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/verifybamid/VerifyBamID/resource/1000g.phase3.100k.b37.vcf.gz.dat.UD"
    db-mu: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/verifybamid/VerifyBamID/resource/1000g.phase3.100k.b37.vcf.gz.dat.mu"
    db-bed: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/verifybamid/VerifyBamID/resource/1000g.phase3.100k.b37.vcf.gz.dat.bed"
  grch38:
    db-V: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.V"
    db-UD: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.UD"
    db-mu: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.mu"
    db-bed: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.bed"
deepvariant:
  grch37:
    calling-ranges: "resources/deepvariant_calling_ranges_grch37.tsv"
  grch38:
    calling-ranges: "resources/deepvariant_calling_ranges_grch38.tsv"
delly:
  grch37:
    exclude-bed: "https://raw.githubusercontent.com/dellytools/delly/main/excludeTemplates/human.hg19.excl.tsv"
  grch38:
    exclude-bed: "https://raw.githubusercontent.com/dellytools/delly/main/excludeTemplates/human.hg38.excl.tsv"
lumpy:
  grch37:
    exclude-bed: "https://raw.githubusercontent.com/hall-lab/speedseq/master/annotations/ceph18.b37.lumpy.exclude.2014-01-15.bed"
  grch38:
    exclude-bed: "https://raw.githubusercontent.com/hall-lab/speedseq/master/annotations/exclude.cnvnator_100bp.GRCh38.20170403.bed"
svaba:
  grch37:
    exclude-bed: "https://raw.githubusercontent.com/hall-lab/speedseq/master/annotations/ceph18.b37.lumpy.exclude.2014-01-15.bed"
  grch38:
    exclude-bed: "https://raw.githubusercontent.com/hall-lab/speedseq/master/annotations/exclude.cnvnator_100bp.GRCh38.20170403.bed"
manta:
  grch37:
    calling-range-bed-gz: "resources/manta_calling_ranges_grch37.bed.gz"
    calling-range-bed-gz-tbi: "resources/manta_calling_ranges_grch37.bed.gz.tbi"
  grch38:
    calling-range-bed-gz: "resources/manta_calling_ranges_grch38.bed.gz"
    calling-range-bed-gz-tbi: "resources/manta_calling_ranges_grch38.bed.gz.tbi"
somalier:
  grch37:
    sites-vcf-gz: "https://github.com/brentp/somalier/files/3412455/sites.GRCh37.vcf.gz"
  grch38:
    sites-vcf-gz: "https://github.com/brentp/somalier/files/3412456/sites.hg38.vcf.gz"
