# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a manifest file that contains
# one row per sample. It can be parsed easily via pandas.
manifest: "config/manifest.tsv"
sample-linking:
  sex: "config/sample_linking_sex.tsv"
  external-ids: "config/sample_linking_external_ids.tsv"
genome-build: "grch38"
apptainer-image-dir: "apptainer_images"

behaviors:
  use-containers: no
  aligner: "bwa"
  qc-type:
    - "lane-specific"
    - "combined-lanes"
  bqsr: yes
  snv-caller: "deepvariant"
  sv-endpoints:
    strict:
      sv-callers:
        - "manta"
        - "lumpy"
        - "delly"
      sv-ensemble:
        min-count: 2
      sv-remove-breakends: yes
    lenient:
      sv-callers:
        - "manta"
      sv-ensemble:
        min-count: 1
      sv-remove-breakends: yes
  outcome: "release"
  symlink-fastqs: no
  remove-duplicates: yes
  import-s3:
    profile-name: "profile-name"
  export-directory: "/path/to/top/level/exports"
  export-s3:
    bucket-name: "s3://bucket-name"
    profile-name: "profile-name"

parameters:
  bwa:
    K: 120000000
  bwa-mem2:
    K: 120000000
  deepvariant:
    number-shards: 16
    docker-version: "1.5.0"
  manta:
    config-ini: "config/configManta.py.ini"
  tiddit:
    min-contig-size: 2000000

references:
  grch38:
    fasta: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
    exclusion-regions-bed: "resources/grch38_encodelist_centromeres_telomeres.bed"
    exons-gtf-gz: "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/hg38.ncbiRefSeq.gtf.gz"
bqsr:
  grch38:
    known-indels-vcf-gz: "s3://broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
    known-indels-vcf-gz-tbi: "s3://broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"
    dbsnp138-vcf: "s3://broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf"
    dbsnp138-vcf-idx: "s3://broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf.idx"
verifybamid2:
  grch38:
    db-V: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.V"
    db-UD: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.UD"
    db-mu: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.mu"
    db-bed: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.bed"
deepvariant:
  grch38:
    calling-ranges: "resources/deepvariant_calling_ranges_grch38.tsv"
delly:
  grch38:
    exclude-bed: "https://raw.githubusercontent.com/dellytools/delly/main/excludeTemplates/human.hg38.excl.tsv"
giraffe:
  grch38:
    graph-gbz: "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.gbz"
    graph-dist: "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.dist"
    graph-min: "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.min"
  chm13:
    graph-gbz: "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-chm13/hprc-v1.1-mc-chm13.gbz"
    graph-dist: "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-chm13/hprc-v1.1-mc-chm13.dist"
    graph-min: "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-chm13/hprc-v1.1-mc-chm13.min"
lumpy:
  grch38:
    exclude-bed: "https://raw.githubusercontent.com/hall-lab/speedseq/master/annotations/exclude.cnvnator_100bp.GRCh38.20170403.bed"
svaba:
  grch38:
    exclude-bed: "https://raw.githubusercontent.com/hall-lab/speedseq/master/annotations/exclude.cnvnator_100bp.GRCh38.20170403.bed"
manta:
  grch38:
    calling-range-bed-gz: "resources/manta_calling_ranges_grch38.bed.gz"
    calling-range-bed-gz-tbi: "resources/manta_calling_ranges_grch38.bed.gz.tbi"
somalier:
  grch38:
    sites-vcf-gz: "https://github.com/brentp/somalier/files/3412456/sites.hg38.vcf.gz"
