queues:
  small:
    - "small"
  large:
    - "large"
    - "large"

tmpdir: "temp"

default:
  threads: 1
  memory: 2000
  queue: "small"
alignstats:
  threads: 4
  memory: 8000
  queue: "small"
apptainer:
  threads: 1
  memory: 8000
  queue: "small"
awscli:
  threads: 1
  memory: 2000
  queue: "small"
bbtools:
  threads: 1
  memory: 32000
  queue: "small"
bcftools:
  threads: 4
  memory: 8000
  queue: "small"
bedtools:
  threads: 1
  memory: 2000
  queue: "small"
bwa_index:
  threads: 1
  memory: 8000
  queue: "small"
bwa_map_and_sort:
  threads: 12
  memory: 500000
  queue: "large"
deepvariant:
  threads: 16
  make_examples_memory: 192000
  call_variants_memory: 480000
  postprocess_variants_memory: 32000
  queue: "large"
delly:
  threads: 1
  memory: 12000
  queue: "small"
duphold:
  threads: 4
  memory: 8000
  queue: "small"
fastp:
  threads: 2
  memory: 8000
  queue: "small"
fastqc:
  threads: 2
  memory: 12000
  queue: "small"
fastq_screen:
  threads: 4
  memory: 8000
  queue: "small"
gatk_bqsr_base_recalibrator:
  threads: 2
  memory: 16000
  queue: "large"
  java_args: "-Xmx8000m -XX:+UseParallelGC -XX:ParallelGCThreads=2"
gatk_bqsr_apply_bqsr:
  threads: 1
  memory: 20000
  queue: "large"
  java_args: "-Xmx10000m"
gatk_collectgcbiasmetrics:
  threads: 1
  memory: 4000
  queue: "small"
  java_args: "-Djava.io.tmpdir=temp/ -XX:CompressedClassSpaceSize=200m -XX:+UseParallelGC -XX:ParallelGCThreads=2 -Xmx3000m"
gatk_collectwgsmetrics:
  threads: 1
  memory: 8000
  queue: "small"
  java_args: "-Djava.io.tmpdir=temp/ -XX:CompressedClassSpaceSize=200m -XX:+UseParallelGC -XX:ParallelGCThreads=2 -Xmx6000m"
gatk_collectmultiplemetrics:
  threads: 1
  memory: 4000
  queue: "small"
  java_args: "-Djava.io.tmpdir=temp/ -XX:CompressedClassSpaceSize=200m -XX:+UseParallelGC -XX:ParallelGCThreads=2 -Xmx3000m"
gatk_create_sequence_dictionary:
  threads: 1
  memory: 10000
  queue: "small"
  java_args: "-Djava.io.tmpdir=temp/ -XX:CompressedClassSpaceSize=200m -XX:+UseParallelGC -XX:ParallelGCThreads=2 -Xmx2000m"
gatk_mark_duplicates:
  threads: 4
  memory: 20000
  queue: "small"
  java_args: "-Djava.io.tmpdir=temp/ -XX:CompressedClassSpaceSize=400m -XX:+UseParallelGC -XX:ParallelGCThreads=2 -Xmx4000m"
manta:
  threads: 4
  memory: 4000
  queue: "small"
mosdepth:
  threads: 1
  memory: 4000
  queue: "small"
multiqc:
  threads: 1
  memory: 4000
  queue: "small"
r:
  threads: 1
  memory: 4000
  queue: "small"
samtools:
  threads: 4
  memory: 8000
  queue: "small"
samtools_sort:
  threads: 2
  memory: 8000
  queue: "small"
smoove:
  threads: 1
  memory: 8000
  queue: "large"
somalier:
  threads: 1
  memory: 1000
  queue: "small"
svaba:
  threads: 8
  memory: 32000
  queue: "large"
svdb:
  threads: 1
  memory: 4000
  queue: "small"
svtools:
  threads: 1
  memory: 2000
  queue: "small"
tiddit:
  threads: 2
  memory: 64000
  queue: "large"
truvari:
  threads: 1
  memory: 4000
  queue: "small"
vep:
  threads: 1
  memory: 4000
  queue: "small"
verifybamid2:
  threads: 2
  memory: 22000
  queue: "small"
