# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a manifest file that contains
# one row per sample. It can be parsed easily via pandas.
manifest: "config/manifest.tsv"
multiqc-read-config: "config/multiqc_read_config.yaml"
multiqc-alignment-config: "config/multiqc_alignment_config.yaml"
genome-build: "grch38"

behaviors:
  aligner: "bwa"
  snv-caller: "deepvariant"
  sv-callers:
    - "delly"
    - "lumpy"
    - "manta"
    - "tiddit"
    - "svaba"
  sv-ensemble:
    min-count: 3
  outcome: "calling"
  symlink-fastqs: no
  trim-adapters-before-alignment: yes

parameters:
  deepvariant:
    number-shards: 16
    docker-version: "1.4.0"
  manta:
    config-ini: "config/configManta.py.ini"

references:
  grch37:
    fasta: "s3://invitae-health-chameleon-dev/reference_data/grch37/human_g1k_v37_modified/human_g1k_v37_modified.fasta"
  grch38:
    fasta: "ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
bqsr:
  grch37:
    known-indels-vcf-gz: "s3://broad-references/hg19/v0/Mills_and_1000G_gold_standard.indels.b37.vcf.gz"
    known-indels-vcf-gz-tbi: "s3://broad-references/hg19/v0/Mills_and_1000G_gold_standard.indels.b37.vcf.gz.tbi"
    dbsnp138-vcf: "s3://broad-references/hg19/v0/Homo_sapiens_assembly19.dbsnp138.vcf"
    dbsnp138-vcf-idx: "s3://broad-references/hg19/v0/Homo_sapiens_assembly19.dbsnp138.vcf.idx"
  grch38:
    known-indels-vcf-gz: "s3://broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
    known-indels-vcf-gz-tbi: "s3://broad-references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"
    dbsnp138-vcf: "s3://broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf"
    dbsnp138-vcf-idx: "s3://broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf.idx"
dnascope:
  grch37:
    model: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/sentieon/SentieonDNAscopeModel1.1.model"
    dbsnp-vcf-gz: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/sentieon/dbsnp_138.b37.vcf.gz"
verifybamid2:
  grch37:
    db-V: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/verifybamid/VerifyBamID/resource/1000g.phase3.100k.b37.vcf.gz.dat.V"
    db-UD: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/verifybamid/VerifyBamID/resource/1000g.phase3.100k.b37.vcf.gz.dat.UD"
    db-mu: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/verifybamid/VerifyBamID/resource/1000g.phase3.100k.b37.vcf.gz.dat.mu"
    db-bed: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/verifybamid/VerifyBamID/resource/1000g.phase3.100k.b37.vcf.gz.dat.bed"
  grch38:
    db-V: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.V"
    db-UD: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.UD"
    db-mu: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.mu"
    db-bed: "https://raw.githubusercontent.com/Griffan/VerifyBamID/master/resource/1000g.phase3.100k.b38.vcf.gz.dat.bed"
octopus:
  error-model: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/octopus/octopus_err_models/novaseq.4a38e55.model"
  forest-model: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/octopus/forests/individual.v0.7.0.v2.forest"
  grch37:
    skip-regions: "s3://invitae-health-chameleon-dev/reference_data/grch37/tool_specific_resources/octopus/b37_all_gaps_octo.txt"
    calling-ranges: "resources/octopus_calling_ranges_grch37.tsv"
deepvariant:
  grch37:
    calling-ranges: "resources/deepvariant_calling_ranges_grch37.tsv"
  grch38:
    calling-ranges: "resources/deepvariant_calling_ranges_grch38.tsv"
delly:
  grch37:
    exclude-bed: "https://raw.githubusercontent.com/dellytools/delly/main/excludeTemplates/human.hg19.excl.tsv"
  grch38:
    exclude-bed: "https://raw.githubusercontent.com/dellytools/delly/main/excludeTemplates/human.hg38.excl.tsv"
lumpy:
  grch37:
    exclude-bed: "https://raw.githubusercontent.com/hall-lab/speedseq/master/annotations/ceph18.b37.lumpy.exclude.2014-01-15.bed"
  grch38:
    exclude-bed: "https://raw.githubusercontent.com/hall-lab/speedseq/master/annotations/exclude.cnvnator_100bp.GRCh38.20170403.bed"
svaba:
  grch37:
    exclude-bed: "https://raw.githubusercontent.com/hall-lab/speedseq/master/annotations/ceph18.b37.lumpy.exclude.2014-01-15.bed"
  grch38:
    exclude-bed: "https://raw.githubusercontent.com/hall-lab/speedseq/master/annotations/exclude.cnvnator_100bp.GRCh38.20170403.bed"
manta:
  grch38:
    calling-range-bed-gz: "resources/manta_calling_ranges_grch38.bed.gz"
    calling-range-bed-gz-tbi: "resources/manta_calling_ranges_grch38.bed.gz.tbi"
somalier:
  grch37:
    sites-vcf-gz: "https://github.com/brentp/somalier/files/3412455/sites.GRCh37.vcf.gz"
  grch38:
    sites-vcf-gz: "https://github.com/brentp/somalier/files/3412456/sites.hg38.vcf.gz"
