max_table_rows:
  3000

fn_clean_exts:
   - ".bwa2a.bam"
   - ".mrkdup.sort.bam"
   - "R1.fastq.gz"
   - "R2.fastq.gz"
   - "R1_001.fastq.gz"
   - "R2_001.fastq.gz"
   - "_qualimap"
   - "sentieon.alignment_summary_metrics.txt"
   - "sentieon.insert_size_metrics_metrics.txt"


extra_fn_clean_exts:
  - type: regex
    pattern: "_R1_001.*"
  - type: regex
    pattern: "_R2_001.*"
  - type: regex
    pattern: "_L00[1-4].*"
  - type: regex
    pattern: ".bwa2a.*"
  - type: regex
    pattern: ".mosdepth.*"


log_filesize_limit: 2000000000 # 2GB limit for parsing

picard_config:
  general_stats_target_coverage:
    - 10
    - 20
    - 30
    - 50

custom_data:
  evenness:
    id: 'evenness'
    section_name: 'evenness'
    description: 'Evenness metrics from Mosdepth'
    format: 'tsv'
    plot_type: 'table'

  alignstats:
    id: 'alignstats'
    section_name: 'alignstats'
    description: 'Alignstats data for General Stats'
    format: 'tsv'
    plot_type: 'generalstats'
    pconfig:
      - sample:
        hidden: False
      - InputFileName:
        hidden: False
      - InputFileSize:
        hidden: False
      - TotalRecords:
        hidden: False
      - UnfilteredRecords:
        hidden: False
      - UnfilteredRecordsPct:
        hidden: False
      - FilteredRecords:
        hidden: False
      - FilteredRecordsPct:
        hidden: False
      - YieldReads:
        hidden: False
      - YieldBases:
        hidden: False
      - UnmappedReads:
        hidden: False
      - UnmappedReadsPct:
        hidden: False
      - UnmappedBases:
        hidden: False
      - UnmappedBasesPct:
        hidden: False
      - DuplicateReads:
        hidden: False
      - DuplicateReadsPct:
        hidden: False
      - DuplicateBases:
        hidden: False
      - DuplicateBasesPct:
        hidden: False
      - MappedReads:
        hidden: False
      - MappedReadsPct:
        hidden: False
      - MappedBases:
        hidden: False
      - MappedBasesPct:
        hidden: False
      - AlignedBases:
        hidden: False
      - AlignedBasesPct:
        hidden: False
      - MatchedBases:
        hidden: False
      - MatchedBasesPct:
        hidden: False
      - MismatchedBases:
        hidden: False
      - MismatchedBasesPct:
        hidden: False
      - InsertedBases:
        hidden: False
      - InsertedBasesPct:
        hidden: False
      - DeletedBases:
        hidden: False
      - DeletedBasesPct:
        hidden: False
      - SoftClippedReads:
        hidden: False
      - SoftClippedReadsPct:
        hidden: False
      - SoftClippedBases:
        hidden: False
      - SoftClippedBasesPct:
        hidden: False
      - PerfectReads:
        hidden: False
      - PerfectReadsPct:
        hidden: False
      - PerfectBases:
        hidden: False
      - PerfectBasesPct:
        hidden: False
      - Q20Bases:
        hidden: False
      - Q20BasesPct:
        hidden: False
      - R1YieldReads:
        hidden: False
      - R1YieldBases:
        hidden: False
      - R1UnmappedReads:
        hidden: False
      - R1UnmappedReadsPct:
        hidden: False
      - R1UnmappedBases:
        hidden: False
      - R1UnmappedBasesPct:
        hidden: False
      - R1MappedReads:
        hidden: False
      - R1MappedReadsPct:
        hidden: False
      - R1MappedBases:
        hidden: False
      - R1MappedBasesPct:
        hidden: False
      - R1AlignedBases:
        hidden: False
      - R1AlignedBasesPct:
        hidden: False
      - R1MatchedBases:
        hidden: False
      - R1MatchedBasesPct:
        hidden: False
      - R1MismatchedBases:
        hidden: False
      - R1MismatchedBasesPct:
        hidden: False
      - R1InsertedBases:
        hidden: False
      - R1InsertedBasesPct:
        hidden: False
      - R1DeletedBases:
        hidden: False
      - R1DeletedBasesPct:
        hidden: False
      - R1SoftClippedReads:
        hidden: False
      - R1SoftClippedReadsPct:
        hidden: False
      - R1SoftClippedBases:
        hidden: False
      - R1SoftClippedBasesPct:
        hidden: False
      - R1PerfectReads:
        hidden: False
      - R1PerfectReadsPct:
        hidden: False
      - R1PerfectBases:
        hidden: False
      - R1PerfectBasesPct:
        hidden: False
      - R1Q20Bases:
        hidden: False
      - R1Q20BasesPct:
        hidden: False
      - R2YieldReads:
        hidden: False
      - R2YieldBases:
        hidden: False
      - R2UnmappedReads:
        hidden: False
      - R2UnmappedReadsPct:
        hidden: False
      - R2UnmappedBases:
        hidden: False
      - R2UnmappedBasesPct:
        hidden: False
      - R2MappedReads:
        hidden: False
      - R2MappedReadsPct:
        hidden: False
      - R2MappedBases:
        hidden: False
      - R2MappedBasesPct:
        hidden: False
      - R2AlignedBases:
        hidden: False
      - R2AlignedBasesPct:
        hidden: False
      - R2MatchedBases:
        hidden: False
      - R2MatchedBasesPct:
        hidden: False
      - R2MismatchedBases:
        hidden: False
      - R2MismatchedBasesPct:
        hidden: False
      - R2InsertedBases:
        hidden: False
      - R2InsertedBasesPct:
        hidden: False
      - R2DeletedBases:
        hidden: False
      - R2DeletedBasesPct:
        hidden: False
      - R2SoftClippedReads:
        hidden: False
      - R2SoftClippedReadsPct:
        hidden: False
      - R2SoftClippedBases:
        hidden: False
      - R2SoftClippedBasesPct:
        hidden: False
      - R2PerfectReads:
        hidden: False
      - R2PerfectReadsPct:
        hidden: False
      - R2PerfectBases:
        hidden: False
      - R2PerfectBasesPct:
        hidden: False
      - R2Q20Bases:
        hidden: False
      - R2Q20BasesPct:
        hidden: False
      - AlignedReadLengthMean:
        hidden: False
      - AlignedReadLengthMedian:
        hidden: False
      - AlignedReadLengthMode:
        hidden: False
      - AlignedReadLengthStandardDeviation:
        hidden: False
      - R1AlignedReadLengthMean:
        hidden: False
      - R1AlignedReadLengthMedian:
        hidden: False
      - R1AlignedReadLengthMode:
        hidden: False
      - R1AlignedReadLengthStandardDeviation:
        hidden: False
      - R2AlignedReadLengthMean:
        hidden: False
      - R2AlignedReadLengthMedian:
        hidden: False
      - R2AlignedReadLengthMode:
        hidden: False
      - R2AlignedReadLengthStandardDeviation:
        hidden: False
      - TotalPairs:
        hidden: False
      - TotalSameChrPairs:
        hidden: False
      - TotalSameChrPairsPct:
        hidden: False
      - UnpairedReads:
        hidden: False
      - UnpairedReadsPct:
        hidden: False
      - R1UnpairedReads:
        hidden: False
      - R1UnpairedReadsPct:
        hidden: False
      - R2UnpairedReads:
        hidden: False
      - R2UnpairedReadsPct:
        hidden: False
      - ChimericReadPairPct:
        hidden: False
      - InsertSizeMean:
        hidden: False
      - InsertSizeMedian:
        hidden: False
      - InsertSizeMode:
        hidden: False
      - InsertSizeStandardDeviation:
        hidden: False
      - WgsTotalReads:
        hidden: False
      - WgsCovDuplicateReads:
        hidden: False
      - WgsCovDuplicateReadsPct:
        hidden: False
      - WgsAlignedReads:
        hidden: False
      - WgsAlignedReadsPct:
        hidden: False
      - WgsReadsPaired:
        hidden: False
      - WgsReadsPairedWithMates:
        hidden: False
      - WgsCoverageMean:
        hidden: False
      - WgsCoverageMedian:
        hidden: False
      - WgsCoverageStandardDeviation:
        hidden: False
      - WgsExpectedAlignedReads:
        hidden: False
      - WgsCalculatedAlignedReads:
        hidden: False
      - WgsCoverageBases1:
        hidden: False
      - WgsCoverageBases1Pct:
        hidden: False
      - WgsCoverageBases10:
        hidden: False
      - WgsCoverageBases10Pct:
        hidden: False
      - WgsCoverageBases15:
        hidden: False
      - WgsCoverageBases15Pct:
        hidden: False
      - WgsCoverageBases20:
        hidden: False
      - WgsCoverageBases20Pct:
        hidden: False
      - WgsCoverageBases30:
        hidden: False
      - WgsCoverageBases30Pct:
        hidden: False
      - WgsCoverageBases40:
        hidden: False
      - WgsCoverageBases40Pct:
        hidden: False
      - WgsCoverageBases50:
        hidden: False
      - WgsCoverageBases50Pct:
        hidden: False
      - WgsCoverageBases60:
        hidden: False
      - WgsCoverageBases60Pct:
        hidden: False
      - WgsCoverageBases70:
        hidden: False
      - WgsCoverageBases70Pct:
        hidden: False
      - WgsCoverageBases100:
        hidden: False
      - WgsCoverageBases100Pct:
        hidden: False
      - WgsCoverageBases500:
        hidden: False
      - WgsCoverageBases500Pct:
        hidden: False
      - WgsCoverageBases1000:
        hidden: False
      - WgsCoverageBases1000Pct:
        hidden: False
      - WgsFilteredOverlapBases:
        hidden: False
      - WgsFilteredLowBaseQualityBases:
        hidden: False
sp:
  alignstats:
    fn: "alignstats_summary_mqc.tsv"
  evenness:
    fn: "evenness_summary_mqc.tsv"
  picard/gcbias:
    fn: "collect_gc_bias_metrics_summary.txt"

module_order:
  - fastqc
  - fastp
  - alignstats
  - somalier
  - picard
  - mosdepth
  - goleft_indexcov
  - qualimap
  - verifybamid
  - custom_content

exclude_modules:
  - snippy
