max_table_rows:
  3000

fn_clean_exts:
   - ".bwa2a.bam"
   - ".mrkdup.sort.bam"
   - "R1.fastq.gz"
   - "R2.fastq.gz"
   - "R1_001.fastq.gz"
   - "R2_001.fastq.gz"
   - "sentieon.alignment_summary_metrics.txt"
   - "sentieon.insert_size_metrics_metrics.txt"


extra_fn_clean_exts:
  - type: regex
    pattern: "_R1_001.*"
  - type: regex
    pattern: "_R2_001.*"
  - type: regex
    pattern: "_L00[1-4].*"
  - type: regex
    pattern: ".bwa2a.*"
  - type: regex
    pattern: ".mosdepth.*"


log_filesize_limit: 2000000000 # 2GB limit for parsing

picard_config:
  general_stats_target_coverage:
    - 10
    - 20
    - 30
    - 50

custom_data:
  alignstats:
    id: 'alignstats'
    section_name: 'alignstats'
    description: 'Alignstats data for General Stats'
    format: 'tsv'
    plot_type: 'generalstats'

sp:
  alignstats:
    fn: "alignstats_summary_mqc.tsv"
  picard/gcbias:
    fn: "collect_gc_bias_metrics_summary.txt"

module_order:
  - fastqc:
      name: 'FastQC (raw)'
      target: ''
      path_filters:
        - 'results/fastqc/*/*_fastqc.zip'
  - fastp
  - fastqc:
      name: 'FastQC (trimmed)'
      target: ''
      path_filters:
        - 'results/fastqc_posttrimming/*/*_fastqc.zip'
  - alignstats
  - somalier
  - picard
  - mosdepth
  - verifybamid
  - custom_content

exclude_modules:
  - snippy
