plots_force_interactive: true

fn_clean_exts:
   - "_001.fastq.gz"
   - ".fastq.gz"
   - "_fastp"
   - "_fastp.fastq.gz"
   - "_001_screen.txt"


module_order:
  - fastqc:
      name: 'FastQC (raw)'
      target: ''
      path_filters:
        - 'results/fastqc/*/*_fastqc.zip'
  - fastp
  - fastqc:
      name: 'FastQC (trimmed)'
      target: ''
      path_filters:
        - 'results/fastqc_posttrimming/*/*_fastqc.zip'
  - fastq_screen
