max_table_rows:
  3000

fn_clean_exts:
   - "R1.fastq.gz"
   - "R2.fastq.gz"
   - "R1_001.fastq.gz"
   - "R2_001.fastq.gz"
   - ".fastq.gz"


extra_fn_clean_exts:
  - type: regex
    pattern: "_R1_001.*"
  - type: regex
    pattern: "_R2_001.*"


log_filesize_limit: 2000000000 # 2GB limit for parsing

module_order:
  - fastqc:
      name: 'FastQC (raw)'
      target: ''
      path_filters:
        - 'results/fastqc/*/*_fastqc.zip'
  - fastp
  - fastqc:
      name: 'FastQC (trimmed)'
      target: ''
      path_filters:
        - 'results/fastqc_posttrimming/*/*_fastqc.zip'
