max_table_rows:
  3000

plots_force_interactive: true

fn_clean_exts:
   - ".snv.vcf.stats"

log_filesize_limit: 2000000000 # 2GB limit for parsing

module_order:
  - bcftools/stats:
      name: 'bcftools/stats (pre-filters)'
      target: ''
      path_filters:
        - 'results/deepvariant/*/*stats'
  - bcftools/stats:
      name: 'bcftools/stats (post-filters)'
      target: ''
      path_filters:
        - 'results/export/*/*stats'
        - 'results/nonexport/*/*stats'
