$schema: "https://json-schema.org/draft/2020-12/schema"
description: global configuration
properties:
  manifest:
    type: string
  sample-logbook:
    type: string
  sample-linking:
    type: object
    properties:
      sex:
        type: string
      external-ids:
        type: string
    additionalProperties: false
  genome-build:
    type: string
    pattern: "^grch[0-9]+$"
  apptainer-image-dir:
    type: string
  behaviors:
    type: object
    properties:
      use-containers:
        type: boolean
        default: no
      aligner:
        type: string
        pattern: "^bwa-mem2$|^bwa$"
      qc-type:
        type: array
        items:
          type: string
          pattern: "^lane-specific$|^combined-lanes$"
      bqsr:
        type: boolean
        default: yes
      snv-caller:
        type: string
        pattern: "^deepvariant$"
      sv-endpoints:
        type: object
        patternProperties:
          "^.*$":
            type: object
            properties:
              sv-callers:
                type: array
                items:
                  type: string
                pattern: "^delly$|^lumpy$|^manta$|^tiddit$|^svaba$"
              sv-ensemble:
                type: object
                properties:
                  min-count:
                    type: integer
                    min: 1
                  required-callers:
                    type: array
                    items:
                      type: string
                      pattern: "^delly$|^lumpy$|^manta$|^tiddit$|^svaba$"
                required:
                  - min-count
                additionalProperties: no
              sv-remove-breakends:
                type: boolean
            required:
              - sv-callers
              - sv-ensemble
              - sv-remove-breakends
            additionalProperties: no
      outcome:
        type: string
        pattern: "^fastqc$|^alignment$|^calling$|^release$"
      symlink-fastqs:
        type: boolean
      trim-adapters-before-alignment:
        oneOf:
          - type: boolean
          - type: string
            pattern: "^legacy$"
      assume-last-sample-sex:
        type: string
        pattern: "^[fF]emale$|^[mM]ale$"
      import-s3:
        type: object
        properties:
          profile-name:
            type: string
        required:
          - profile-name
        additionalProperties: no
      export-directory:
        type: string
      export-s3:
        type: object
        properties:
          bucket-name:
            type: string
          profile-name:
            type: string
        required:
          - bucket-name
        additionalProperties: false
    required:
      - aligner
      - snv-caller
      - sv-endpoints
      - outcome
      - symlink-fastqs
      - trim-adapters-before-alignment
    additionalProperties: no
  parameters:
    type: object
    properties:
      bwa:
        type: object
        properties:
          K:
            type: integer
        required:
          - K
        additionalProperties: false
      bwa-mem2:
        type: object
        properties:
          K:
            type: integer
        required:
          - K
        additionalProperties: false
      deepvariant:
        type: object
        properties:
          number-shards:
            type: integer
            min: 1
          docker-version:
            type: string
        required:
          - number-shards
          - docker-version
        additionalProperties: no
      manta:
        type: object
        properties:
          config-ini:
            type: string
        required:
          - config-ini
        additionalProperties: no
      tiddit:
        type: object
        properties:
          min-contig-size:
            type: integer
            min: 0
        required:
          - min-contig-size
        additionalProperties: no
    required:
      - deepvariant
      - manta
      - tiddit
    additionalProperties: no
  references:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          fasta:
            type: string
          exclusion-regions-bed:
            type: string
          exons-gtf-gz:
            type: string
        required:
          - fasta
          - exclusion-regions-bed
          - exons-gtf-gz
        additionalProperties: no
    required:
      - grch38
  bqsr:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          known-indels-vcf-gz:
            type: string
          known-indels-vcf-gz-tbi:
            type: string
          dbsnp138-vcf:
            type: string
          dbsnp138-vcf-idx:
            type: string
        required:
          - known-indels-vcf-gz
          - known-indels-vcf-gz-tbi
          - dbsnp138-vcf
          - dbsnp138-vcf-idx
        additionalProperties: no
  somalier:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          sites-vcf-gz:
            type: string
        required:
          - sites-vcf-gz
        additionalProperties: no
  verifybamid2:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          db-V:
            type: string
          db-UD:
            type: string
          db-mu:
            type: string
          db-bed:
            type: string
        required:
          - db-V
          - db-UD
          - db-mu
          - db-bed
        additionalProperties: no
    required:
      - grch38
  deepvariant:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          calling-ranges:
            type: string
        required:
          - calling-ranges
        additionalProperties: no
    required:
      - grch38
  delly:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          exclude-bed:
            type: string
        required:
          - exclude-bed
        additionalProperties: no
  lumpy:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          exclude-bed:
            type: string
        required:
          - exclude-bed
        additionalProperties: no
  svaba:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          exclude-bed:
            type: string
        required:
          - exclude-bed
        additionalProperties: no
  manta:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          calling-range-bed-gz:
            type: string
          calling-range-bed-gz-tbi:
            type: string
        required:
          - calling-range-bed-gz
          - calling-range-bed-gz-tbi
        additionalProperties: no
required:
  - manifest
  - genome-build
  - behaviors
  - references
  - bqsr
  - somalier
  - verifybamid2
  - deepvariant
  - delly
  - lumpy
  - svaba
  - manta
additionalProperties: yes
