$schema: "https://json-schema.org/draft/2020-12/schema"
description: global configuration
properties:
  manifest:
    type: string
  multiqc-config:
    type: string
  genome-build:
    type: string
    pattern: "^grch[0-9]+$"
  references:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          fasta:
            type: string
          fasta-dict:
            type: string
          reportable-regions:
            type: string
        required:
          - fasta
          - fasta-dict
          - reportable-regions
        additionalProperties: no
    required:
      - grch37
  dnascope:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          model:
            type: string
          dbsnp-vcf-gz:
            type: string
          dbsnp-vcf-gz-tbi:
            type: string
    required:
      - grch37
  verifybamid2:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          db-V:
            type: string
          db-UD:
            type: string
          db-mu:
            type: string
          db-bed:
            type: string
        required:
          - db-V
          - db-UD
          - db-mu
          - db-bed
        additionalProperties: no
    required:
      - grch37
required:
  - manifest
  - multiqc-config
  - genome-build
  - references
  - dnascope
  - verifybamid2
additionalProperties: no
