$schema: "https://json-schema.org/draft/2020-12/schema"
description: global configuration
properties:
  manifest:
    type: string
  multiqc-read-config:
    type: string
  multiqc-alignment-config:
    type: string
  genome-build:
    type: string
    pattern: "^grch[0-9]+$"
  behaviors:
    type: object
    properties:
      aligner:
        type: string
        pattern: "^bwa-mem2$|^bwa$"
      snv-caller:
        type: string
        pattern: "^octopus$|^deepvariant$"
      sv-callers:
        type: array
        items:
          type: string
          pattern: "^delly$|^lumpy$|^manta$|^tiddit$|^svaba$"
      sv-ensemble:
        type: object
        properties:
          min-count:
            type: integer
            min: 1
          required-callers:
            type: array
            items:
              type: string
              pattern: "^delly$|^lumpy$|^manta$|^tiddit$|^svaba$"
        required:
          - min-count
        additionalProperties: no
      outcome:
        type: string
        pattern: "^fastqc$|^alignment$|^calling$"
      symlink-fastqs:
        type: boolean
      trim-adapters-before-alignment:
        oneOf:
          - type: boolean
          - type: string
            pattern: "^legacy$"
    required:
      - aligner
      - snv-caller
      - sv-callers
      - sv-ensemble
      - outcome
      - symlink-fastqs
      - trim-adapters-before-alignment
    additionalProperties: no
  parameters:
    type: object
    properties:
      deepvariant:
        type: object
        properties:
          number-shards:
            type: integer
            min: 1
          docker-version:
            type: string
        required:
          - number-shards
          - docker-version
        additionalProperties: no
      manta:
        type: object
        properties:
          config-ini:
            type: string
        required:
          - config-ini
        additionalProperties: no
    required:
      - deepvariant
      - manta
    additionalProperties: no
  references:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          fasta:
            type: string
          reportable-regions:
            type: string
        required:
          - fasta
          - reportable-regions
        additionalProperties: no
    required:
      - grch37
  bqsr:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          known-indels-vcf-gz:
            type: string
          known-indels-vcf-gz-tbi:
            type: string
          dbsnp138-vcf:
            type: string
          dbsnp138-vcf-idx:
            type: string
        required:
          - known-indels-vcf-gz
          - known-indels-vcf-gz-tbi
          - dbsnp138-vcf
          - dbsnp138-vcf-idx
        additionalProperties: no
  dnascope:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          model:
            type: string
          dbsnp-vcf-gz:
            type: string
        required:
          - model
          - dbsnp-vcf-gz
        additionalProperties: no
    required:
      - grch37
  verifybamid2:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          db-V:
            type: string
          db-UD:
            type: string
          db-mu:
            type: string
          db-bed:
            type: string
        required:
          - db-V
          - db-UD
          - db-mu
          - db-bed
        additionalProperties: no
    required:
      - grch37
  octopus:
    type: object
    properties:
      forest-model:
        type: string
      error-model:
        type: string
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          skip-regions:
            type: string
          calling-ranges:
            type: string
        required:
          - skip-regions
          - calling-ranges
        additionalProperties: no
    required:
      - forest-model
      - error-model
      - grch37
  deepvariant:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          calling-ranges:
            type: string
        required:
          - calling-ranges
        additionalProperties: no
    required:
      - grch37
  lumpy:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          exclude-bed:
            type: string
        required:
          - exclude-bed
        additionalProperties: no
required:
  - manifest
  - multiqc-read-config
  - multiqc-alignment-config
  - genome-build
  - behaviors
  - references
  - bqsr
  - dnascope
  - verifybamid2
  - octopus
  - deepvariant
  - lumpy
additionalProperties: no
