$schema: "https://json-schema.org/draft/2020-12/schema"
description: tool/rule-specific resource configuration
properties:
  queues:
    patternProperties:
      "^.*$":
        type: array
        items:
          type: string
  tmpdir:
    type: string
  default: &defaults
    type: object
    properties:
      threads:
        type: integer
        min: 1
      memory:
        type: integer
        min: 100
      queue:
        type: string
    required:
      - threads
      - memory
      - queue
    additionalProperties: false
  default_with_java: &defaults_with_java
    type: object
    properties:
      threads:
        type: integer
        min: 1
      memory:
        type: integer
        min: 100
      queue:
        type: string
      java_args:
        type: string
    required:
      - threads
      - memory
      - queue
      - java_args
    additionalProperties: false
  alignstats:
    <<: *defaults
  awscli:
    <<: *defaults
  bcftools:
    <<: *defaults
  bbtools:
    <<: *defaults
  bedtools:
    <<: *defaults
  bwa_index:
    <<: *defaults
  bwa_map_and_sort:
    <<: *defaults
  deepvariant:
    type: object
    properties:
      threads:
        type: integer
        min: 1
      make_examples_memory:
        type: integer
        min: 100
      call_variants_memory:
        type: integer
        min: 100
      postprocess_variants_memory:
        type: integer
        min: 100
      queue:
        type: string
    required:
      - threads
      - make_examples_memory
      - call_variants_memory
      - postprocess_variants_memory
      - queue
    additionalProperties: false
  delly:
    <<: *defaults
  duphold:
    <<: *defaults
  fastp:
    <<: *defaults
  fastqc:
    <<: *defaults
  gatk_bqsr_base_recalibrator:
    <<: *defaults_with_java
  gatk_bqsr_apply_bqsr:
    <<: *defaults_with_java
  gatk_collectgcbiasmetrics:
    <<: *defaults_with_java
  gatk_collectwgsmetrics:
    <<: *defaults_with_java
  gatk_collectmultiplemetrics:
    <<: *defaults_with_java
  gatk_create_sequence_dictionary:
    <<: *defaults_with_java
  gatk_mark_duplicates:
    <<: *defaults_with_java
  manta:
    <<: *defaults
  mosdepth:
    <<: *defaults
  multiqc:
    <<: *defaults
  r:
    <<: *defaults
  samtools:
    <<: *defaults
  smoove:
    <<: *defaults
  somalier:
    <<: *defaults
  svaba:
    <<: *defaults
  svdb:
    <<: *defaults
  svtools:
    <<: *defaults
  tiddit:
    <<: *defaults
  truvari:
    <<: *defaults
  vep:
    <<: *defaults
  verifybamid2:
    <<: *defaults
required:
  - queues
  - tmpdir
  - default
  - alignstats
  - awscli
  - bcftools
  - bedtools
  - bwa_index
  - bwa_map_and_sort
  - deepvariant
  - delly
  - duphold
  - fastp
  - fastqc
  - gatk_bqsr_base_recalibrator
  - gatk_bqsr_apply_bqsr
  - gatk_collectgcbiasmetrics
  - gatk_collectwgsmetrics
  - gatk_collectmultiplemetrics
  - gatk_create_sequence_dictionary
  - gatk_mark_duplicates
  - manta
  - mosdepth
  - r
  - samtools
  - smoove
  - somalier
  - svaba
  - svdb
  - svtools
  - tiddit
  - truvari
  - vep
  - verifybamid2
additionalProperties: false
